version: 2.1

orbs:
  slack: circleci/slack@3.2.0

workflows:
  version: 2
  test:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout
      - slack/status:
          success_message: OK
          mentions: ryym
          webhook: https://hooks.slack.com/services/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
  
